# Generated by Django 4.1.2 on 2022-10-13 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_alter_user_is_admin_alter_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')])),
                ('Vehicle_type', models.CharField(choices=[('TWO_WHEELER', '2'), ('THREE_WHEELER', '3'), ('FOUR_WHEELER', '4')], max_length=50)),
                ('vehicle_model', models.CharField(max_length=23)),
                ('vehicle_description', models.TextField()),
            ],
        ),
    ]
